services:
  - type: web
    name: minecraft-pvp
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --skip-generate && npm run build
    startCommand: npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
